### ISSUE TITLE
Production is using testnet URL

### ISSUE THREAD

**Issue by gssvv** [avnu-labs/avnu-sdk#138] opened 2023-09-03 18:34 UTC
In `services.ts` you can find the logic that defines the API endpoint. For me, it seems like BASE_URL must be a production one.
https://github.com/avnu-labs/avnu-sdk/blob/182213a7e3111ec6c874eb67a21f6174294c74c4/src/services.ts#L21

But in fact, it's still goerli:
https://github.com/avnu-labs/avnu-sdk/blob/182213a7e3111ec6c874eb67a21f6174294c74c4/src/constants.ts#L4

That seems like a bug and I think this should be updated. Or was it intentional?

**Comment by gssvv** [comment] 2023-09-03 18:36
@florian-bellotti let me know if I can pick this up

**Comment by gssvv** [comment] 2023-09-03 18:37
Temporary workaround


```javascript
const PRODUCTION_BASE_URL = "https://starknet.api.avnu.fi";

anvu
  .fetchQuotes(
    {
      sellTokenAddress:
        "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
      buyTokenAddress:
        "0x53c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8",
      sellAmount: parseEther("1").toBigInt(),
    },
    {
      baseUrl: PRODUCTION_BASE_URL,
    }
  )
```

**Comment by florian-bellotti** [comment] 2023-09-28 18:48
Hi @gssvv. Thanks a lot and sorry for the delay. The issue is now fixed. You can use the latest version: 1.2.0

**Closed by florian-bellotti** 2023-09-28 18:48 UTC
